services:
    Dominique92.VTTrack.listener:
        class: Dominique92\VTTrack\event\listener
        arguments:
            - '@dbal.conn'
            - '@request'
        tags:
            - { name: event.listener }
