services:
    Dominique92.MyPhpBB.listener:
        class: Dominique92\MyPhpBB\event\listener
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@auth'
            - '@language'
        tags:
            - { name: event.listener }
